set(0, ...
    'defaultaxesfontsize',   24, ...
    'defaultaxeslinewidth',   1, ...
    'defaultlinelinewidth',   1, ...
    'defaultpatchlinewidth',  1, ...
    'defaultaxesticklength',  [0.02 0.02], ...
    'defaultaxesfontweight','normal', ...
    'DefaultFigurePaperpositionmode','manual',...
    'DefaultFigurePaperUnits','centimeters',...
    'DefaultFigurePaperPosition',[1 1 8 8/1.41]*2,...
    'defaultaxesfontname','Arial',...
    'DefaultLineMarkerSize',10);
