set(0, ...
    'defaultaxesfontsize',   10, ...
    'defaultaxeslinewidth',   0.5, ...
    'defaultlinelinewidth',   0.5, ...
    'defaultpatchlinewidth',  0.5, ...
    'defaultaxesticklength',  [0.02 0.02], ...
    'defaultaxesfontweight','bold', ...
    'DefaultFigurePaperpositionmode','manual',...
    'DefaultFigurePaperUnits','centimeters',...
    'DefaultFigurePaperPosition',[0 0 8.46 8.46]/1.5,...
    'defaultaxesfontname','Helvetica',...
		'DefaultLineMarkerSize',10);%, ...
	  %'DefaultLineLineWidth',1);
