function [ output_args ] = MATLABPHASINGSTART( input_args )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                          x ');pause(.01)
disp('                        ____')
disp('                       /    \')
disp('                      /      \')
disp('                      \      /')
disp('                       \____/')
disp('                        ****                    ')
disp('                       * * * *                    ')
disp('                      *  * *  *                ')
disp('                     *  *   *  *                 ')
disp('                    *   *   *   *                 ')
disp('                   *   *     *   *                ')
disp('                  *    *     *    *               ')
disp('                 ###################                                            ')
disp('                          |                    ')
disp('                          V                    ');pause(.15)
disp('                 _____________________                              ')
disp('                |                     |         ')
disp('                |          .          |         ')
disp('                |          .          |         ')
disp('                |          .          |         ')
disp('                |  . .. . .O.. . .    |         ')
disp('                |          .          |         ')
disp('                |          .          |         ')
disp('                |          .          |         ')
disp('                |_____________________|                              ')
disp('                                              ')
disp('                                              ')
disp('                                              ')
disp('                                              ')
disp('                                              ')



end

