function newData1=importfile1(fileToRead1,textlines)
%IMPORTFILE1(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-Feb-2013 16:40:23

try
    textlines;
catch
    textlines=34;
end

DELIMITER = ' ';
HEADERLINES = textlines;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end



end

